In [2]:
import pygame
import numpy as np
import matplotlib.pyplot as plt

In [4]:
axis = np.array([1, 2, 3])
angle = 0.1 * np.pi

In [17]:
np.meshgrid(axis, axis, indexing='ij')

[array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])]

In [15]:
np.multiply(*np.meshgrid(axis, axis))

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [16]:
A_hat = np.multiply(*np.meshgrid(axis, axis))
A_star = np.array([[0, -axis[2], axis[1]],
                   [axis[2], 0, -axis[0]],
                   [-axis[1], axis[0], 0]])
rotational_matrix = A_hat + np.cos(angle) * (np.identity(A_hat.shape[0]) - A_hat) + np.sin(angle) * A_star

print(f"A_hat:\n{A_hat}")
print(f"A_star:\n{A_star}")
print(f"rotational_matrix:\n{rotational_matrix}")

A_hat:
[[1 2 3]
 [2 4 6]
 [3 6 9]]
A_star:
[[ 0 -3  2]
 [ 3  0 -1]
 [-2  1  0]]
rotational_matrix:
[[ 1.         -0.82916402  0.76486444]
 [ 1.02493795  1.14683045 -0.01535609]
 [-0.47120354  0.6026779   1.39154787]]
