In [1]:
import numpy as np
import src.quaternion as q
import importlib

importlib.reload(q)

<module 'src.quaternion' from '/Users/alfred/Documents/rotations/src/quaternion.py'>

In [66]:
axis = np.array([[1., 6., 6.],
        [0., 0., 0.],
        [9., 7., 8.]])
angle = np.random.randint(0, 10, (3,)).astype(np.float64)

axis, angle

(array([[1., 6., 6.],
        [0., 0., 0.],
        [9., 7., 8.]]),
 array([0., 4., 2.]))

In [67]:
axis_norm = np.linalg.norm(axis, axis=-1)
axis_norm

array([ 8.54400375,  0.        , 13.92838828])

In [68]:
mask = axis_norm != 0
mask

array([ True, False,  True])

In [69]:
axis_norm[mask]

array([ 8.54400375, 13.92838828])

In [70]:
axis_norm[mask][None].T

array([[ 8.54400375],
       [13.92838828]])

In [71]:
axis[mask]

array([[1., 6., 6.],
       [9., 7., 8.]])

In [72]:
axis[mask] / axis_norm[mask][None].T

array([[0.11704115, 0.70224688, 0.70224688],
       [0.64616234, 0.50257071, 0.57436653]])

In [73]:
axis_normalized = axis.copy()
axis_normalized[mask] /= axis_norm[mask][None].T
axis, axis_normalized

(array([[1., 6., 6.],
        [0., 0., 0.],
        [9., 7., 8.]]),
 array([[0.11704115, 0.70224688, 0.70224688],
        [0.        , 0.        , 0.        ],
        [0.64616234, 0.50257071, 0.57436653]]))

In [74]:
axis[2] / np.linalg.norm(axis[2])

array([0.64616234, 0.50257071, 0.57436653])

In [76]:
np.cos(angle / 2)

array([ 1.        , -0.41614684,  0.54030231])

In [83]:
result = np.insert(axis, 0, np.cos(angle / 2), axis=-1)
result

array([[ 1.        ,  1.        ,  6.        ,  6.        ],
       [-0.41614684,  0.        ,  0.        ,  0.        ],
       [ 0.54030231,  9.        ,  7.        ,  8.        ]])

In [89]:
np.sin(angle / 2)

array([0.        , 0.90929743, 0.84147098])

In [92]:
result_copy = result.copy()
result_copy2 = result.copy()
result_copy[..., 1:] *= np.sin(angle / 2)[None].T
result_copy2.T[1:]  *= np.sin(angle / 2)
result, result_copy, result_copy2

(array([[ 1.        ,  1.        ,  6.        ,  6.        ],
        [-0.41614684,  0.        ,  0.        ,  0.        ],
        [ 0.54030231,  9.        ,  7.        ,  8.        ]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-0.41614684,  0.        ,  0.        ,  0.        ],
        [ 0.54030231,  7.57323886,  5.89029689,  6.73176788]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-0.41614684,  0.        ,  0.        ,  0.        ],
        [ 0.54030231,  7.57323886,  5.89029689,  6.73176788]]))

In [51]:
a = np.arange(9).reshape(3,3)
b = a
a, b


(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [52]:
b[[0, 2]] = b[[0, 2]] * 99

In [53]:
a, b

(array([[  0,  99, 198],
        [  3,   4,   5],
        [594, 693, 792]]),
 array([[  0,  99, 198],
        [  3,   4,   5],
        [594, 693, 792]]))